version: "1.0.0"
services:
  grocery:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=grocerydb
      - MONGO_INITDB_ROOT_PASSWORD=grocerydbpass
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
